const orchardStore={profile:'visne-profile-v1',logs:'visne-logs-v1'};
const money=n=>Number(n).toLocaleString('tr-TR',{minimumFractionDigits:2,maximumFractionDigits:2});
const value=id=>document.getElementById(id).value;
const safe=text=>String(text).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const weatherCodes={0:['Açık','☀️'],1:['Çoğunlukla açık','🌤️'],2:['Parçalı bulutlu','⛅'],3:['Kapalı','☁️'],45:['Sisli','🌫️'],48:['Kırağılı sis','🌫️'],51:['Hafif çisenti','🌦️'],53:['Çisenti','🌦️'],55:['Yoğun çisenti','🌧️'],61:['Hafif yağmur','🌦️'],63:['Yağmur','🌧️'],65:['Kuvvetli yağmur','🌧️'],71:['Hafif kar','🌨️'],73:['Kar','🌨️'],75:['Yoğun kar','❄️'],80:['Sağanak','🌦️'],81:['Sağanak','🌧️'],82:['Kuvvetli sağanak','⛈️'],95:['Gök gürültülü','⛈️'],96:['Dolu riski','⛈️'],99:['Şiddetli dolu riski','⛈️']};
async function loadYesilkoyWeather(){const current=document.getElementById('weather-current'),days=document.getElementById('weather-days'),alerts=document.getElementById('weather-alerts'),updated=document.getElementById('weather-updated');current.innerHTML='<p>Yeşilköy tahmini yükleniyor…</p>';days.innerHTML='';alerts.innerHTML='';try{const url='https://api.open-meteo.com/v1/forecast?latitude=37.1832&longitude=29.8124&current=temperature_2m,relative_humidity_2m,weather_code,wind_speed_10m&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max,wind_speed_10m_max&timezone=Europe%2FIstanbul&forecast_days=7';const response=await fetch(url);if(!response.ok)throw new Error('Tahmin alınamadı');const data=await response.json(),condition=weatherCodes[data.current.weather_code]||['Değişken','🌤️'];current.innerHTML=`<strong>${Math.round(data.current.temperature_2m)}°</strong><div><b>${condition[1]} ${condition[0]}</b><span>Nem %${data.current.relative_humidity_2m} · Rüzgâr ${Math.round(data.current.wind_speed_10m)} km/sa</span></div>`;const warnings=[];data.daily.time.forEach((date,i)=>{const day=new Date(date+'T12:00:00').toLocaleDateString('tr-TR',{weekday:'long'});if(data.daily.temperature_2m_min[i]<=0)warnings.push(`<div class="weather-alert danger">${day}: ${Math.round(data.daily.temperature_2m_min[i])} °C — don riski</div>`);if(data.daily.wind_speed_10m_max[i]>=30)warnings.push(`<div class="weather-alert">${day}: kuvvetli rüzgâr ${Math.round(data.daily.wind_speed_10m_max[i])} km/sa</div>`)});alerts.innerHTML=warnings.slice(0,4).join('')||'<div class="weather-alert">Önümüzdeki 7 günde otomatik don veya kuvvetli rüzgâr uyarısı görünmüyor.</div>';days.innerHTML=data.daily.time.map((date,i)=>{const info=weatherCodes[data.daily.weather_code[i]]||['Değişken','🌤️'];return `<article class="weather-day"><b>${new Date(date+'T12:00:00').toLocaleDateString('tr-TR',{weekday:'short'})}</b><span class="weather-icon" aria-hidden="true">${info[1]}</span><strong>${Math.round(data.daily.temperature_2m_max[i])}° / ${Math.round(data.daily.temperature_2m_min[i])}°</strong><span>Yağış %${data.daily.precipitation_probability_max[i]}</span><span>${safe(info[0])}</span></article>`}).join('');updated.textContent=`Son güncelleme: ${new Date().toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit'})}`}catch(error){current.innerHTML='<strong>Tahmin yüklenemedi</strong><span>İnternet bağlantınızı kontrol edip yeniden deneyin.</span>';alerts.innerHTML='';updated.textContent=''}}
document.getElementById('refresh-weather').addEventListener('click',loadYesilkoyWeather);loadYesilkoyWeather();
const profileForm=document.getElementById('profile-form');
const savedProfile=JSON.parse(localStorage.getItem(orchardStore.profile)||'null');
if(savedProfile)Object.entries(savedProfile).forEach(([id,val])=>{const el=document.getElementById(id);if(el)el.value=val});
profileForm.addEventListener('submit',e=>{e.preventDefault();const profile={};profileForm.querySelectorAll('input,select').forEach(el=>profile[el.id]=el.value);localStorage.setItem(orchardStore.profile,JSON.stringify(profile));document.getElementById('profile-result').textContent='Bahçe profili bu cihazda kaydedildi.';document.getElementById('water-trees').value=profile['garden-trees']||200});

document.getElementById('daily-form').addEventListener('submit',e=>{e.preventDefault();const stage=value('daily-stage'),min=+value('daily-min'),temp=+value('daily-temp'),wind=+value('daily-wind'),rain=+value('daily-rain'),wet=value('daily-leaf')==='wet',items=[];let cls='';if(['Tomurcuk','Çiçeklenme'].includes(stage)&&min<=0){items.push(`Gece don riski var: beklenen en düşük ${min} °C. Bahçenin alçak noktasındaki gerçek ölçümü izleyin.`);cls='risk-high'}if(wind>15){items.push('Rüzgâr sürüklenme riskini artırıyor; ilaçlama için uygun görünmüyor.');cls='risk-high'}else if(wind>10){items.push('Rüzgâr sınırda; ürün etiketini ve bahçe içi ölçümü kontrol edin.');cls=cls||'risk-watch'}if(rain>=50){items.push('Yakın yağış uygulamayı yıkayabilir; etiketteki yağmura dayanma süresini kontrol edin.');cls=cls||'risk-watch'}if(wet)items.push('Yaprak ıslak; uygulama ve hastalık riski açısından kuruma zamanını değerlendirin.');if(stage==='Çiçeklenme')items.push('Arılar çalışırken uygulama yapmayın; arı koruma hükümleri ve etiket esastır.');if(temp<5||temp>30){items.push(`Uygulama sıcaklığı ${temp} °C; ürün etiketindeki sıcaklık sınırını özellikle kontrol edin.`);cls=cls||'risk-watch'}if(!items.length)items.push('Girilen temel değerlerde belirgin bir kırmızı bayrak görülmedi. Etiket, saha ölçümü ve yerel tahmini yine kontrol edin.');const out=document.getElementById('daily-result');out.className=`decision-result ${cls}`;out.innerHTML=`<strong>${cls==='risk-high'?'Bugün dikkat: uygulamayı erteleyin':cls==='risk-watch'?'Koşullar sınırda':'Temel koşullar uygun görünüyor'}</strong><ul>${items.map(x=>`<li>${x}</li>`).join('')}</ul>`});

document.getElementById('irrigation-form').addEventListener('submit',e=>{e.preventDefault();const trees=+value('water-trees'),emitters=+value('water-emitters'),flow=+value('water-flow'),target=+value('water-target'),hours=target/(emitters*flow),total=trees*target;document.getElementById('irrigation-result').innerHTML=`<strong>Yaklaşık ${hours.toLocaleString('tr-TR',{maximumFractionDigits:2})} saat çalıştırın</strong><div class="result-numbers"><span><b>${money(total)} L</b>toplam hedef su</span><span><b>${money(emitters*flow)} L/saat</b>ağaç başına debi</span><span><b>${money(total/1000)} m³</b>toplam hacim</span></div>`});

const calculateProfit=()=>{const y=+value('profit-yield'),price=+value('profit-price'),cost=['cost-fertilizer','cost-protection','cost-labor','cost-other'].reduce((s,id)=>s+(+value(id)),0),revenue=y*price,net=revenue-cost,unit=y?cost/y:0,area=+(document.getElementById('garden-area').value||5);document.getElementById('profit-result').innerHTML=`<strong>${net>=0?'Tahmini sezon sonucu':'Tahmini sezon zararı'}: ${money(net)} ₺</strong><div class="result-numbers"><span><b>${money(revenue)} ₺</b>brüt gelir</span><span><b>${money(cost)} ₺</b>toplam gider</span><span><b>${money(unit)} ₺/kg</b>ürün maliyeti</span><span><b>${money(area?y/area:0)} kg/da</b>dekar verimi</span><span><b>${money(area?cost/area:0)} ₺/da</b>dekar gideri</span><span><b>${money(area?net/area:0)} ₺/da</b>dekar sonucu</span></div>`};document.getElementById('profit-form').addEventListener('submit',e=>{e.preventDefault();calculateProfit()});

let logs=JSON.parse(localStorage.getItem(orchardStore.logs)||'[]');const logDate=document.getElementById('log-date');logDate.value=new Date().toISOString().slice(0,10);const renderLogs=()=>{const filter=value('log-filter'),shown=filter==='all'?logs:logs.filter(x=>x.type===filter),list=document.getElementById('log-list');list.innerHTML=shown.length?shown.map(x=>`<article class="log-item"><span>${new Date(x.date+'T12:00:00').toLocaleDateString('tr-TR')}</span><strong>${safe(x.type)}</strong><span>${safe(x.note)}${x.quantity?` · ${money(x.quantity)} birim`:''}</span><em>${x.cost?money(x.cost)+' ₺':''}</em><button type="button" data-delete="${x.id}" aria-label="Kaydı sil">Sil</button></article>`).join(''):'<p class="empty-log">Henüz bu filtrede kayıt yok.</p>';renderSeasonSummary()};
document.getElementById('log-form').addEventListener('submit',e=>{e.preventDefault();const quantity=+value('log-quantity'),unitPrice=+value('log-unit-price'),enteredCost=+value('log-cost');logs.unshift({id:Date.now(),date:value('log-date'),type:value('log-type'),quantity,unitPrice,cost:enteredCost||(quantity*unitPrice),note:value('log-note')});localStorage.setItem(orchardStore.logs,JSON.stringify(logs));e.target.reset();logDate.value=new Date().toISOString().slice(0,10);renderLogs()});document.getElementById('log-filter').addEventListener('change',renderLogs);document.getElementById('log-list').addEventListener('click',e=>{const id=e.target.dataset.delete;if(!id)return;logs=logs.filter(x=>x.id!==+id);localStorage.setItem(orchardStore.logs,JSON.stringify(logs));renderLogs()});
document.getElementById('export-log').addEventListener('click',()=>{if(!logs.length)return alert('İndirilecek kayıt yok.');const rows=[['Tarih','İşlem','Miktar','Birim Fiyat','Tutar','Not'],...logs.map(x=>[x.date,x.type,x.quantity||0,x.unitPrice||0,x.cost,x.note])],csv='\uFEFF'+rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(';')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='visne-bahcesi-kayitlari.csv';a.click();URL.revokeObjectURL(a.href)});renderLogs();

const expenseTypes=['Gübreleme','Bitki koruma','Budama','Sulama','Masraf'];
function renderSeasonSummary(){const expense=logs.filter(x=>expenseTypes.includes(x.type)).reduce((s,x)=>s+(+x.cost||0),0),harvest=logs.filter(x=>x.type==='Hasat').reduce((s,x)=>s+(+x.quantity||0),0),sales=logs.filter(x=>x.type==='Hasat').reduce((s,x)=>s+((+x.quantity||0)*(+x.unitPrice||0)),0),net=sales-expense,area=+(document.getElementById('garden-area').value||5);document.getElementById('season-summary').innerHTML=`<span><b>${money(expense)} ₺</b>Kayıtlı gider</span><span><b>${money(harvest)} kg</b>Hasat</span><span><b>${money(sales)} ₺</b>Hasat değeri</span><span><b class="${net<0?'negative':''}">${money(net)} ₺</b>Kayıtlı sonuç</span><span><b>${money(area?harvest/area:0)} kg/da</b>Dekar verimi</span>`}
document.getElementById('fill-costs').addEventListener('click',()=>{const sum=type=>logs.filter(x=>x.type===type).reduce((s,x)=>s+(+x.cost||0),0);document.getElementById('cost-fertilizer').value=sum('Gübreleme');document.getElementById('cost-protection').value=sum('Bitki koruma');document.getElementById('cost-labor').value=sum('Budama');document.getElementById('cost-other').value=sum('Sulama')+sum('Masraf');const harvest=logs.filter(x=>x.type==='Hasat').reduce((s,x)=>s+(+x.quantity||0),0);if(harvest)document.getElementById('profit-yield').value=harvest;calculateProfit()});
document.getElementById('backup-data').addEventListener('click',()=>{const data={version:2,exportedAt:new Date().toISOString(),profile:JSON.parse(localStorage.getItem(orchardStore.profile)||'null'),logs};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='visne-bahcesi-yedek.json';a.click();URL.revokeObjectURL(a.href)});
document.getElementById('restore-data').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{const data=JSON.parse(await file.text());if(!Array.isArray(data.logs))throw new Error();if(!confirm('Mevcut kayıtlar yedekteki kayıtlarla değiştirilsin mi?'))return;logs=data.logs;if(data.profile)localStorage.setItem(orchardStore.profile,JSON.stringify(data.profile));localStorage.setItem(orchardStore.logs,JSON.stringify(logs));alert('Yedek başarıyla yüklendi.');location.reload()}catch{alert('Bu dosya geçerli bir Vişne Bahçesi yedeği değil.')}finally{e.target.value=''}});

document.getElementById('symptom-form').addEventListener('submit',e=>{e.preventDefault();const place=value('symptom-place'),spread=value('symptom-spread'),damage=value('symptom-damage'),tips={leaf:['Yaprağın ön ve arka yüzünü çekin.','Lekede delikleşme, sarı hale veya kıvrılma olup olmadığına bakın.'],fruit:['Sağlam ve belirtili meyveyi yan yana çekin.','Çökme, akıntı, küf veya böcek giriş deliğini not edin.'],branch:['Zamk, yara ve kabuk sınırını yakından çekin.','Dalın tamamını ve kesitini göstermeden kesim yapmayın.'],flower:['Kuruyan çiçek demetini ve bağlı olduğu sürgünü çekin.','Belirtinin yağış veya dondan sonra başlayıp başlamadığını not edin.']}[place];if(spread==='all')tips.push('Bahçe geneli dağılım; beslenme, su, don veya uygulama etkisini de düşündürür.');if(spread==='patch')tips.push('Kümeli dağılımda toprak, drenaj ve bulaşma yönünü ayrıca kontrol edin.');if(damage==='yes')tips.push('Don veya yara öyküsü hastalıkla karışabilir; olay tarihini yazın.');document.getElementById('symptom-result').innerHTML=`<strong>Kesin teşhisten önce şu kanıtları toplayın</strong><ul>${tips.map(x=>`<li>${x}</li>`).join('')}</ul>`;document.getElementById('symptom-whatsapp').href=`https://wa.me/905413350929?text=${encodeURIComponent('Merhaba, Vişne Bahçesi belirti kontrolünden geliyorum. Belirti yeri: '+place+', dağılım: '+spread+'. Fotoğrafları ekliyorum.')}`});
document.getElementById('clear-data').addEventListener('click',()=>{if(confirm('Bahçe profili ve tüm kayıtlar bu cihazdan silinsin mi?')){localStorage.removeItem(orchardStore.profile);localStorage.removeItem(orchardStore.logs);location.reload()}});
