const orchardStore={profile:'visne-profile-v1',logs:'visne-logs-v1'};
const money=n=>Number(n).toLocaleString('tr-TR',{minimumFractionDigits:2,maximumFractionDigits:2});
const value=id=>document.getElementById(id).value;
const safe=text=>String(text).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const profileForm=document.getElementById('profile-form');
const savedProfile=JSON.parse(localStorage.getItem(orchardStore.profile)||'null');
if(savedProfile)Object.entries(savedProfile).forEach(([id,val])=>{const el=document.getElementById(id);if(el)el.value=val});
profileForm.addEventListener('submit',e=>{e.preventDefault();const profile={};profileForm.querySelectorAll('input,select').forEach(el=>profile[el.id]=el.value);localStorage.setItem(orchardStore.profile,JSON.stringify(profile));document.getElementById('profile-result').textContent='Bahçe profili bu cihazda kaydedildi.';document.getElementById('water-trees').value=profile['garden-trees']||200});

document.getElementById('daily-form').addEventListener('submit',e=>{e.preventDefault();const stage=value('daily-stage'),min=+value('daily-min'),temp=+value('daily-temp'),wind=+value('daily-wind'),rain=+value('daily-rain'),wet=value('daily-leaf')==='wet',items=[];let cls='';if(['Tomurcuk','Çiçeklenme'].includes(stage)&&min<=0){items.push(`Gece don riski var: beklenen en düşük ${min} °C. Bahçenin alçak noktasındaki gerçek ölçümü izleyin.`);cls='risk-high'}if(wind>15){items.push('Rüzgâr sürüklenme riskini artırıyor; ilaçlama için uygun görünmüyor.');cls='risk-high'}else if(wind>10){items.push('Rüzgâr sınırda; ürün etiketini ve bahçe içi ölçümü kontrol edin.');cls=cls||'risk-watch'}if(rain>=50){items.push('Yakın yağış uygulamayı yıkayabilir; etiketteki yağmura dayanma süresini kontrol edin.');cls=cls||'risk-watch'}if(wet)items.push('Yaprak ıslak; uygulama ve hastalık riski açısından kuruma zamanını değerlendirin.');if(stage==='Çiçeklenme')items.push('Arılar çalışırken uygulama yapmayın; arı koruma hükümleri ve etiket esastır.');if(temp<5||temp>30){items.push(`Uygulama sıcaklığı ${temp} °C; ürün etiketindeki sıcaklık sınırını özellikle kontrol edin.`);cls=cls||'risk-watch'}if(!items.length)items.push('Girilen temel değerlerde belirgin bir kırmızı bayrak görülmedi. Etiket, saha ölçümü ve yerel tahmini yine kontrol edin.');const out=document.getElementById('daily-result');out.className=`decision-result ${cls}`;out.innerHTML=`<strong>${cls==='risk-high'?'Bugün dikkat: uygulamayı erteleyin':cls==='risk-watch'?'Koşullar sınırda':'Temel koşullar uygun görünüyor'}</strong><ul>${items.map(x=>`<li>${x}</li>`).join('')}</ul>`});

document.getElementById('irrigation-form').addEventListener('submit',e=>{e.preventDefault();const trees=+value('water-trees'),emitters=+value('water-emitters'),flow=+value('water-flow'),target=+value('water-target'),hours=target/(emitters*flow),total=trees*target;document.getElementById('irrigation-result').innerHTML=`<strong>Yaklaşık ${hours.toLocaleString('tr-TR',{maximumFractionDigits:2})} saat çalıştırın</strong><div class="result-numbers"><span><b>${money(total)} L</b>toplam hedef su</span><span><b>${money(emitters*flow)} L/saat</b>ağaç başına debi</span><span><b>${money(total/1000)} m³</b>toplam hacim</span></div>`});

document.getElementById('profit-form').addEventListener('submit',e=>{e.preventDefault();const y=+value('profit-yield'),price=+value('profit-price'),cost=['cost-fertilizer','cost-protection','cost-labor','cost-other'].reduce((s,id)=>s+(+value(id)),0),revenue=y*price,net=revenue-cost,unit=y?cost/y:0;document.getElementById('profit-result').innerHTML=`<strong>${net>=0?'Tahmini sezon sonucu':'Tahmini sezon zararı'}: ${money(net)} ₺</strong><div class="result-numbers"><span><b>${money(revenue)} ₺</b>brüt gelir</span><span><b>${money(cost)} ₺</b>toplam gider</span><span><b>${money(unit)} ₺/kg</b>ürün maliyeti</span></div>`});

let logs=JSON.parse(localStorage.getItem(orchardStore.logs)||'[]');const logDate=document.getElementById('log-date');logDate.value=new Date().toISOString().slice(0,10);const renderLogs=()=>{const filter=value('log-filter'),shown=filter==='all'?logs:logs.filter(x=>x.type===filter),list=document.getElementById('log-list');list.innerHTML=shown.length?shown.map(x=>`<article class="log-item"><span>${new Date(x.date+'T12:00:00').toLocaleDateString('tr-TR')}</span><strong>${safe(x.type)}</strong><span>${safe(x.note)}</span><em>${x.cost?money(x.cost)+' ₺':''}</em><button type="button" data-delete="${x.id}" aria-label="Kaydı sil">Sil</button></article>`).join(''):'<p class="empty-log">Henüz bu filtrede kayıt yok.</p>'};
document.getElementById('log-form').addEventListener('submit',e=>{e.preventDefault();logs.unshift({id:Date.now(),date:value('log-date'),type:value('log-type'),cost:+value('log-cost'),note:value('log-note')});localStorage.setItem(orchardStore.logs,JSON.stringify(logs));e.target.reset();logDate.value=new Date().toISOString().slice(0,10);renderLogs()});document.getElementById('log-filter').addEventListener('change',renderLogs);document.getElementById('log-list').addEventListener('click',e=>{const id=e.target.dataset.delete;if(!id)return;logs=logs.filter(x=>x.id!==+id);localStorage.setItem(orchardStore.logs,JSON.stringify(logs));renderLogs()});
document.getElementById('export-log').addEventListener('click',()=>{if(!logs.length)return alert('İndirilecek kayıt yok.');const rows=[['Tarih','İşlem','Tutar','Not'],...logs.map(x=>[x.date,x.type,x.cost,x.note])],csv='\uFEFF'+rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(';')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='visne-bahcesi-kayitlari.csv';a.click();URL.revokeObjectURL(a.href)});renderLogs();

document.getElementById('symptom-form').addEventListener('submit',e=>{e.preventDefault();const place=value('symptom-place'),spread=value('symptom-spread'),damage=value('symptom-damage'),tips={leaf:['Yaprağın ön ve arka yüzünü çekin.','Lekede delikleşme, sarı hale veya kıvrılma olup olmadığına bakın.'],fruit:['Sağlam ve belirtili meyveyi yan yana çekin.','Çökme, akıntı, küf veya böcek giriş deliğini not edin.'],branch:['Zamk, yara ve kabuk sınırını yakından çekin.','Dalın tamamını ve kesitini göstermeden kesim yapmayın.'],flower:['Kuruyan çiçek demetini ve bağlı olduğu sürgünü çekin.','Belirtinin yağış veya dondan sonra başlayıp başlamadığını not edin.']}[place];if(spread==='all')tips.push('Bahçe geneli dağılım; beslenme, su, don veya uygulama etkisini de düşündürür.');if(spread==='patch')tips.push('Kümeli dağılımda toprak, drenaj ve bulaşma yönünü ayrıca kontrol edin.');if(damage==='yes')tips.push('Don veya yara öyküsü hastalıkla karışabilir; olay tarihini yazın.');document.getElementById('symptom-result').innerHTML=`<strong>Kesin teşhisten önce şu kanıtları toplayın</strong><ul>${tips.map(x=>`<li>${x}</li>`).join('')}</ul>`;document.getElementById('symptom-whatsapp').href=`https://wa.me/905413350929?text=${encodeURIComponent('Merhaba, Vişne Bahçesi belirti kontrolünden geliyorum. Belirti yeri: '+place+', dağılım: '+spread+'. Fotoğrafları ekliyorum.')}`});
document.getElementById('clear-data').addEventListener('click',()=>{if(confirm('Bahçe profili ve tüm kayıtlar bu cihazdan silinsin mi?')){localStorage.removeItem(orchardStore.profile);localStorage.removeItem(orchardStore.logs);location.reload()}});
