const healthSymptoms={
  leaf:[['spots','Leke, sararma veya delikleşme'],['curl','Kıvrılma ve yapışkanlık'],['bronze','Bronzlaşma / beneklenme'],['scorch','Kenar yanıklığı']],
  flower:[['dry','Çiçek ve sürgün kuruması'],['brown','Kahverengileşme ve zamk'],['drop','Zayıf tutum / dökülme']],
  fruit:[['rot','Yumuşama veya çürüme'],['spot','Leke / çöküntü'],['crack','Çatlama'],['worm','Giriş deliği / larva']],
  branch:[['gum','Zamklanma'],['dieback','Uçtan geriye kuruma'],['hole','Delik ve talaş'],['wound','Kabuk yarası / çökme']],
  whole:[['yellow','Genel sararma ve zayıflık'],['wilt','Ani solma'],['uneven','Düzensiz gelişme'],['earlyfall','Erken yaprak dökümü']]
};
const healthGuides={
  'leaf-spots':{title:'Yaprak lekesi grubu',level:'watch',label:'Yakın takip',possible:'Vişne yaprak lekesi veya başka yaprak leke etmenleri; delikleşmede fizyolojik ya da kimyasal zarar da düşünülür.',checks:['Yaprağın alt yüzünde açık renkli oluşum var mı?','Lekelerin çevresinde sarı hale ve erken döküm var mı?','Belirti yağışlı dönemden sonra mı arttı?']},
  'leaf-curl':{title:'Emici zararlı veya stres olasılığı',level:'watch',label:'Yakın takip',possible:'Yaprak biti kolonisi, sıcaklık-su stresi veya uygulama sürüklenmesi birbiriyle karışabilir.',checks:['Yaprak altında koloni, yapışkan salgı ve karınca arayın.','Yeni sürgünlerle yaşlı yaprakları karşılaştırın.','Komşu parselde yakın tarihli uygulama olup olmadığını not edin.']},
  'leaf-bronze':{title:'Akar veya yaprak stresi grubu',level:'watch',label:'Büyüteçle kontrol',possible:'Akarlar, sıcak-kuru koşullar veya bazı beslenme dengesizlikleri benzer görünüm oluşturabilir.',checks:['Yaprak altını büyüteçle inceleyin.','Sağlıklı ve belirtili yaprağı yan yana karşılaştırın.','Belirtinin bahçe kenarında mı başladığını kaydedin.']},
  'leaf-scorch':{title:'Bulaşıcı olmayan nedenleri önce ayırın',level:'watch',label:'Su ve uygulama kontrolü',possible:'Su stresi, tuzluluk, sıcak rüzgâr, kök sorunu veya uygulama yanığı.',checks:['Toprak nemini yalnız yüzeyden değil kök derinliğinden kontrol edin.','Son gübre ve yaprak uygulamasının tarih-doz kaydını bulun.','Damlatıcıların gerçek debisini karşılaştırın.']},
  'flower-dry':{title:'Çiçek yanıklığı–don ayrımı',level:'urgent',label:'Aynı gün inceleyin',possible:'Monilya çiçek yanıklığı, geç don veya bakteriyel sorun olasılıkları birbirine benzeyebilir.',checks:['Kuruma çiçek demetinden sürgüne ilerliyor mu?','Düşük ve soğuk noktalarda zarar daha mı ağır?','Kesitte renk değişimi veya zamk var mı?']},
  'flower-brown':{title:'Çiçek ve sürgün enfeksiyonu olasılığı',level:'urgent',label:'Aynı gün inceleyin',possible:'Fungal veya bakteriyel etmenler ile don yarası birlikte değerlendirilmeli.',checks:['Yeni ve eski yaraların sınırını fotoğraflayın.','Yağış, don ve çiçeklenme tarihini not edin.','Şüpheli dala temas eden aleti başka ağaçta kullanmadan temizleyin.']},
  'flower-drop':{title:'Tozlanma ve çevre koşulları',level:'watch',label:'Kayıtları karşılaştırın',possible:'Don, soğuk-yağışlı hava, zayıf arı faaliyeti, beslenme veya su dengesi.',checks:['Tam çiçek ve don tarihlerini karşılaştırın.','Günün farklı saatlerinde arı hareketini hatırlayın.','Ağaçlar ve çeşitler arasında tutum farkı var mı?']},
  'fruit-rot':{title:'Meyve çürüklüğü grubu',level:'urgent',label:'Hızlı ayırın',possible:'Monilya/kahverengi çürüklük; çatlak, dolu, kuş veya hasat yaraları enfeksiyon girişini kolaylaştırabilir.',checks:['Çürükte halka biçimli sporlanma var mı?','Meyvede çatlak veya yara bulunuyor mu?','Mumyalaşmış eski meyveleri ve yakın meyve kümelerini kontrol edin.']},
  'fruit-spot':{title:'Meyve lekesi veya fiziksel zarar',level:'watch',label:'Örnek toplayın',possible:'Hastalık, güneş yanığı, dolu ve uygulama lekesi ayrılmalı.',checks:['Lekenin güneşe bakan yüzde yoğunlaşıp yoğunlaşmadığına bakın.','Sağlam ve belirtili meyveyi birlikte çekin.','Son yağış, dolu ve uygulama tarihini not edin.']},
  'fruit-crack':{title:'Çatlama ve ikincil çürüme riski',level:'watch',label:'Hasadı planlayın',possible:'Yağış-sulama dalgalanması ve çeşit hassasiyeti; açık çatlaklar çürüklük riskini artırır.',checks:['Yağış veya sulama sonrası artışı kaydedin.','Çatlağın sap çevresi mi yanak kısmında mı olduğunu çekin.','Çatlak meyveyi sağlam kasaya karıştırmayın.']},
  'fruit-worm':{title:'Meyve zararlısı olasılığı',level:'urgent',label:'Tuzak ve meyve kontrolü',possible:'Kiraz sineği veya başka meyve zararlıları; yalnız dış iz kesin teşhis değildir.',checks:['Şüpheli meyveyi keserek içini kontrol edin.','Tuzak sayımlarını tarihleriyle karşılaştırın.','Hasat öncesi süre nedeniyle ürün seçmeden yetkili uzmana danışın.']},
  'branch-gum':{title:'Zamklanma bir sonuçtur, teşhis değildir',level:'urgent',label:'Yara kaynağını bulun',possible:'Bakteriyel kanser, don, budama yarası, fiziksel stres veya dal zararlısı.',checks:['Kabuk altı dokuda renk değişimi var mı?','Yara gövdeyi veya ana dalı kuşatıyor mu?','Don ve budama tarihiyle başlangıcı karşılaştırın.']},
  'branch-dieback':{title:'Dal geriye ölümü',level:'urgent',label:'Yayılmayı işaretleyin',possible:'Kanserler, çiçek yanıklığı, kış zararı, kök stresi veya mekanik zarar.',checks:['Sağlam-hastalıklı doku sınırını bulun.','Aynı yöndeki dallarda tekrar edip etmediğini kontrol edin.','Ağaç numarası ve etkilenen dal yönünü kaydedin.']},
  'branch-hole':{title:'Kabuk ve odun zararlısı olasılığı',level:'urgent',label:'Gövdeyi tarayın',possible:'Dal zararlıları veya önceden zayıflamış dokuda ikincil böcek faaliyeti.',checks:['Delik çevresinde taze talaş veya akıntı arayın.','Stresli ağaçların kümelenmesini işaretleyin.','Kök boğazı ve ana dalları da inceleyin.']},
  'branch-wound':{title:'Kanser–yara ayrımı',level:'urgent',label:'Sınırı belgeleyin',possible:'Bakteriyel/fungal kanser, don çatlağı, budama veya sürtünme yarası.',checks:['Yaranın kenarını ve tamamını ölçekle çekin.','Yağışlı havada gereksiz kesim yapmayın.','Aynı ağaçtaki eski yaraları karşılaştırın.']},
  'whole-yellow':{title:'Kök, su ve beslenme birlikte okunmalı',level:'watch',label:'Analiz ve nem kontrolü',possible:'Su fazlası/eksikliği, kök sorunu, pH veya besin dengesizliği.',checks:['Sağlıklı ağaçla sürgün uzunluğu ve yaprak rengini karşılaştırın.','Kök derinliğinde nem ve drenajı kontrol edin.','Toprak-yaprak analizini tek bir elemente bakmadan değerlendirin.']},
  'whole-wilt':{title:'Ani solma acil belirtidir',level:'urgent',label:'Aynı gün uzman',possible:'Kök boğazı, iletim dokusu, ağır su stresi veya gövdeyi kuşatan zarar.',checks:['Gövde ve kök boğazını çepeçevre inceleyin.','Damlatıcı arızası ve toprak doygunluğunu kontrol edin.','Ağacı ve komşularını numaralandırıp yayılmayı izleyin.']},
  'whole-uneven':{title:'Bahçe içi değişkenlik',level:'watch',label:'Haritalayın',possible:'Toprak, drenaj, sulama eşitsizliği, fidan/anaç farkı veya kronik kök sorunu.',checks:['Zayıf ağaçları bahçe krokisinde işaretleyin.','Damlatıcı debilerini güçlü ağaçlarla karşılaştırın.','Toprak yapısı ve eğim sınırlarıyla örtüşüyor mu?']},
  'whole-earlyfall':{title:'Erken yaprak dökümü',level:'urgent',label:'Gelecek sezonu koruyun',possible:'Yaprak lekesi, su stresi, kök sorunu veya uygulama etkisi.',checks:['Dökümden önceki yaprak belirtilerini fotoğraflayın.','Alt-iç taç ile üst taçtaki şiddeti karşılaştırın.','Yağış, sulama ve son uygulama tarihlerini çıkarın.']}
};
const organ=document.getElementById('health-organ'),symptom=document.getElementById('health-symptom'),spread=document.getElementById('health-spread'),result=document.getElementById('health-result');
function fillHealthSymptoms(){symptom.innerHTML=healthSymptoms[organ.value].map(([value,label])=>`<option value="${value}">${label}</option>`).join('')}
function renderHealthResult(event){event?.preventDefault();const guide=healthGuides[`${organ.value}-${symptom.value}`],spreadNote={single:'Tekil dağılım; yara, kök, damlatıcı ve ağaç özelindeki etkenleri ayrıca inceleyin.',patch:'Kümeli dağılım; drenaj, toprak, sulama hattı ve bulaşma yönünü krokiye işleyin.',all:'Bahçe geneli dağılım; hava olayı, su-besleme ve son uygulama etkisini önce dışlayın.'}[spread.value];result.className=`health-result ${guide.level}`;result.innerHTML=`<span class="result-label">${guide.label}</span><h3>${guide.title}</h3><p><b>Olası grup:</b> ${guide.possible}</p><p><b>Dağılım yorumu:</b> ${spreadNote}</p><b>Şimdi kontrol edin:</b><ul>${guide.checks.map(item=>`<li>${item}</li>`).join('')}</ul>`}
organ.addEventListener('change',()=>{fillHealthSymptoms();renderHealthResult()});document.getElementById('health-form').addEventListener('submit',renderHealthResult);fillHealthSymptoms();renderHealthResult();
