const menuButton=document.querySelector('.menu-button');const navigation=document.querySelector('#site-nav');
if(navigation&&!navigation.querySelector('a[href="bahcem.html"]')){const orchardLink=document.createElement('a');orchardLink.href='bahcem.html';orchardLink.textContent='Bahçem';const contactLink=navigation.querySelector('a[href="iletisim.html"]');navigation.insertBefore(orchardLink,contactLink||null)}
if(menuButton&&navigation){menuButton.addEventListener('click',()=>{const open=menuButton.getAttribute('aria-expanded')==='true';menuButton.setAttribute('aria-expanded',String(!open));navigation.classList.toggle('open',!open)});navigation.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{navigation.classList.remove('open');menuButton.setAttribute('aria-expanded','false')}))}
const year=document.querySelector('#year');if(year)year.textContent=new Date().getFullYear();

const monthData=[['Ocak','Don, kar yükü ve kırık dalları kontrol edin.'],['Şubat','Budama planını don riskine göre hazırlayın.'],['Mart','Tomurcuk gelişimi ve drenajı izleyin.'],['Nisan','Çiçeklenme, geç don ve arı faaliyetini takip edin.'],['Mayıs','Meyve tutumu, sürgün ve yaprakları kaydedin.'],['Haziran','Su stresi, meyve gelişimi ve zararlı riskini izleyin.'],['Temmuz','Olgunluk, hasat ve hızlı gölgelemeyi planlayın.'],['Ağustos','Hasat sonrası ağaç sağlığını kontrol edin.'],['Eylül','Toprak-yaprak analizi ve sonbahar bakımını planlayın.'],['Ekim','Yaprak dökümü, hijyen ve organik madde planını yapın.'],['Kasım','Drenajı, fidan ihtiyacını ve hastalıklı materyali yönetin.'],['Aralık','Sezon kayıtlarını, ekipmanı ve yeni yıl bütçesini gözden geçirin.']];
const monthIndex=new Date().getMonth(),monthLabel=document.querySelector('#current-month-label'),monthTask=document.querySelector('#current-month-task');if(monthLabel)monthLabel.textContent=`${monthData[monthIndex][0]} ayında bahçede`;if(monthTask)monthTask.textContent=monthData[monthIndex][1];

const stages={dinlenme:{title:'Dinlenme dönemi',text:'Ağaç yapraksızken taç yapısı, kuru dallar, gövde yaraları ve bahçenin drenajı daha kolay görülür.',tasks:['Geçmiş sezon kayıtlarını karşılaştırın','Budama aletlerini temizleyip bileyin','Toprak analizini ve girdi planını tamamlayın'],warning:'Don riski yüksekken acele budama yapmayın; her ağaca aynı şiddeti uygulamayın.'},tomurcuk:{title:'Tomurcuk kabarması',text:'Takvim tarihinden çok tomurcuğun gerçek gelişimi önemlidir. Bahçenin farklı noktaları aynı hızda ilerlemeyebilir.',tasks:['Temsilî ağaçlarda dönemi kaydedin','Yağış ve sıcaklık tahminini izleyin','Önceki yıl hastalık görülen noktaları kontrol edin'],warning:'Fenolojiyi görmeden rutin uygulama başlatmayın.'},cicek:{title:'Çiçeklenme',text:'Geç don, yağış, rüzgâr ve arı hareketi meyve tutumunu birlikte etkiler.',tasks:['Alçak ve kapalı noktaları ayrıca izleyin','Çiçek başlangıcı ve tam çiçek tarihini yazın','Arı faaliyetini günün farklı saatlerinde gözleyin'],warning:'Arıların aktif olduğu saatlerde riskli uygulamalardan kaçının; etiketi esas alın.'},meyve:{title:'Meyve gelişimi',text:'Ürün yükü, sürgün gelişimi ve kök bölgesi nemi birlikte okunmalıdır.',tasks:['Damlatıcı debilerini karşılaştırın','Meyve ve sürgün gelişimini haftalık kaydedin','Yaprak altı ve meyvelerde belirti arayın'],warning:'Yalnızca yüzey nemine bakarak sulama kararı vermeyin.'},hasat:{title:'Hasat sonrası',text:'Yapraklar yeni sezon için depo oluşturmaya devam eder; bakım hasatla bitmez.',tasks:['Kırık dal ve erken yaprak dökümünü işaretleyin','Verim ve ıskarta miktarını kaydedin','Sulamayı bir anda kesmeden ihtiyaca göre azaltın'],warning:'Hasat bitti diye ağacı susuz bırakmayın veya gereksiz azot vermeyin.'}};
const stagePanel=document.querySelector('#stage-panel');function showStage(key){const item=stages[key];if(!stagePanel||!item)return;stagePanel.innerHTML=`<div><h3>${item.title}</h3><p>${item.text}</p><ul>${item.tasks.map(task=>`<li>${task}</li>`).join('')}</ul></div><div class="stage-warning"><strong>Bu dönemde sık hata</strong>${item.warning}</div>`}document.querySelectorAll('[data-stage]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-stage]').forEach(item=>item.classList.remove('active'));button.classList.add('active');showStage(button.dataset.stage)}));showStage('dinlenme');

const mixForm=document.querySelector('#mix-form');if(mixForm)mixForm.addEventListener('submit',event=>{event.preventDefault();const tank=Number(document.querySelector('#tank-volume').value),dose=Number(document.querySelector('#label-dose').value),unit=document.querySelector('#dose-unit').value,result=document.querySelector('#mix-result');const total=tank*dose/100;result.textContent=`${tank.toLocaleString('tr-TR')} L su için: ${total.toLocaleString('tr-TR',{maximumFractionDigits:2})} ${unit}`});

const storageKey='visneBahcesiKayitlari';const recordForm=document.querySelector('#record-form'),recordList=document.querySelector('#record-list'),recordDate=document.querySelector('#record-date');if(recordDate)recordDate.value=new Date().toISOString().slice(0,10);function getRecords(){try{return JSON.parse(localStorage.getItem(storageKey))||[]}catch{return[]}}function esc(value){return String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}function renderRecords(){if(!recordList)return;const records=getRecords();recordList.innerHTML=records.length?records.slice(0,4).map((r,i)=>`<div class="record-item"><strong>${new Date(`${r.date}T12:00:00`).toLocaleDateString('tr-TR')}</strong><span>${esc(r.type)}: ${esc(r.note)}</span><button type="button" data-delete="${i}" aria-label="Kaydı sil">×</button></div>`).join(''):'<p class="record-empty">Henüz kayıt yok. İlk bahçe notunuzu ekleyin.</p>'}if(recordForm)recordForm.addEventListener('submit',event=>{event.preventDefault();const records=getRecords();records.unshift({date:recordDate.value,type:document.querySelector('#record-type').value,note:document.querySelector('#record-note').value.trim()});localStorage.setItem(storageKey,JSON.stringify(records.slice(0,20)));recordForm.reset();recordDate.value=new Date().toISOString().slice(0,10);renderRecords()});if(recordList)recordList.addEventListener('click',event=>{const button=event.target.closest('[data-delete]');if(!button)return;const records=getRecords();records.splice(Number(button.dataset.delete),1);localStorage.setItem(storageKey,JSON.stringify(records));renderRecords()});renderRecords();

if(!document.querySelector('link[href="contact.css"]')){const contactStyles=document.createElement('link');contactStyles.rel='stylesheet';contactStyles.href='contact.css';document.head.appendChild(contactStyles)}
if(!document.querySelector('#producer-contact-form')){const whatsapp=document.createElement('a');whatsapp.className='whatsapp-fab';whatsapp.href='iletisim.html';whatsapp.setAttribute('aria-label','WhatsApp üzerinden iletişim kur');whatsapp.innerHTML='<b aria-hidden="true">●</b><span>Bahçenizi sorun</span>';document.body.appendChild(whatsapp)}
const articleBody=document.querySelector('.article-body');if(articleBody){const title=document.querySelector('h1')?.textContent.trim()||document.title;const feedback=document.createElement('aside');feedback.className='guide-feedback';feedback.innerHTML=`<strong>Bu rehber işinize yaradı mı?</strong><p>Kısa geri bildiriminiz, sonraki içerikleri gerçek üretici ihtiyaçlarına göre geliştirmemize yardım eder.</p><div class="feedback-actions"><a href="https://wa.me/905413350929?text=${encodeURIComponent(`Merhaba, “${title}” rehberi işime yaradı.`)}" target="_blank" rel="noopener">Evet, yararlı oldu</a><a href="https://wa.me/905413350929?text=${encodeURIComponent(`Merhaba, “${title}” rehberinde şu bilgi eksik kaldı: `)}" target="_blank" rel="noopener">Eksik bilgi bildir</a><a href="iletisim.html">Bahçemle ilgili soru sor</a></div>`;articleBody.appendChild(feedback)}
