const tr=(n,d=1)=>Number(n).toLocaleString('tr-TR',{maximumFractionDigits:d});
const yieldForm=document.querySelector('#yield-form');
if(yieldForm)yieldForm.addEventListener('submit',event=>{event.preventDefault();const area=+document.querySelector('#yield-area').value,trees=+document.querySelector('#yield-trees').value,samples=+document.querySelector('#yield-samples').value,average=+document.querySelector('#yield-average').value,loss=+document.querySelector('#yield-loss').value/100,out=document.querySelector('#yield-result');if(samples>trees){out.innerHTML='<strong>Örnek ağaç sayısı toplam ağaç sayısını geçemez.</strong>';return}const net=trees*average*(1-loss),low=net*.85,high=net*1.15,perDa=net/area;out.innerHTML='<strong>Tahmini net hasat: '+tr(net,0)+' kg</strong><div class="output-grid"><span><b>'+tr(low,0)+'–'+tr(high,0)+' kg</b>ihtiyatlı tahmin aralığı</span><span><b>'+tr(perDa,0)+' kg/da</b>tahmini dekar verimi</span><span><b>'+samples+' ağaç</b>örneklem büyüklüğü</span></div>'});
const frostForm=document.querySelector('#frost-map-form');
if(frostForm)frostForm.addEventListener('submit',event=>{event.preventDefault();const readings=[{name:'Alt bölüm',value:+document.querySelector('#frost-low').value},{name:'Orta bölüm',value:+document.querySelector('#frost-mid').value},{name:'Üst bölüm',value:+document.querySelector('#frost-high').value}],sorted=[...readings].sort((a,b)=>a.value-b.value),delta=sorted[2].value-sorted[0].value,period=document.querySelector('#frost-period').value,out=document.querySelector('#frost-map-result');const risk=sorted[0].value<=0?'Donma noktasının altında ölçüm var.':'Tüm ölçümler donma noktasının üzerinde.';out.innerHTML='<strong>En soğuk nokta: '+sorted[0].name+' · '+tr(sorted[0].value)+' °C</strong><div class="output-grid"><span><b>'+tr(delta)+' °C</b>bahçe içi sıcaklık farkı</span><span><b>'+period+'</b>seçilen dönem</span><span><b>'+risk+'</b>ölçüm özeti</span></div>'});
const questions=[
 {q:'Tam çiçeklenmede yapraklar ıslak, rüzgâr 18 km/sa ve kısa sürede yağış bekleniyor. Ne yapılmalı?',o:['Hemen uygulama yapılmalı','Koşullar yeniden değerlendirilip uygulama ertelenmeli','Doz iki katına çıkarılmalı'],a:1,e:'Yüksek rüzgâr sürüklenmeyi, yakın yağış ise yıkanma riskini artırabilir. Etiket ve arı güvenliği ayrıca kontrol edilmelidir.'},
 {q:'Toprak yüzeyi koyu ve ıslak görünüyor. Bu, kök derinliğinde yeterli su olduğunu kanıtlar mı?',o:['Evet','Hayır, kök derinliği ayrıca kontrol edilmeli'],a:1,e:'Yüzey görünümü tek başına yeterli değildir; damlatıcının yanındaki kök bölgesinden kontrol gerekir.'},
 {q:'Bahçenin sadece yol kenarındaki ağaçlarından verim örneği almak doğru mudur?',o:['Evet, ulaşması kolaydır','Hayır, örnekler bahçeye dengeli dağıtılmalıdır'],a:1,e:'Yol kenarı, alçak bölüm veya tek sıra bahçenin tamamını temsil etmeyebilir.'},
 {q:'Hasat biter bitmez sulama tamamen kesilmeli mi?',o:['Evet','Hayır, yaprak ve kök nemi izlenerek sürdürülmeli'],a:1,e:'Sağlıklı yapraklar hasattan sonra da çalışır; sulama ihtiyaca göre azaltılmalı, birden kesilmemelidir.'},
 {q:'Tek bir yaprak belirtisi görülünce doğrudan ilaç seçmek doğru mudur?',o:['Evet','Hayır, dağılım, fenoloji, hava ve geçmiş işlemler birlikte incelenmeli'],a:1,e:'Benzer belirtiler don, su stresi, beslenme sorunu veya farklı hastalıklardan kaynaklanabilir.'}
];let qi=0,score=0,answered=false;const qText=document.querySelector('#quiz-question'),qOptions=document.querySelector('#quiz-options'),qFeedback=document.querySelector('#quiz-feedback'),qNext=document.querySelector('#quiz-next'),qCount=document.querySelector('#quiz-count'),qScore=document.querySelector('#quiz-score');
function renderQuestion(){if(!qText)return;answered=false;const item=questions[qi];qCount.textContent=(qi+1)+' / '+questions.length;qScore.textContent='Doğru: '+score;qText.textContent=item.q;qOptions.innerHTML=item.o.map((option,index)=>'<button type="button" data-answer="'+index+'">'+option+'</button>').join('');qFeedback.textContent='';qNext.hidden=true}
if(qOptions)qOptions.addEventListener('click',event=>{const button=event.target.closest('button[data-answer]');if(!button||answered)return;answered=true;const chosen=+button.dataset.answer,item=questions[qi];[...qOptions.children].forEach((b,index)=>{b.disabled=true;if(index===item.a)b.classList.add('correct')});if(chosen===item.a){score++;qFeedback.innerHTML='<strong>Doğru.</strong> '+item.e}else{button.classList.add('wrong');qFeedback.innerHTML='<strong>Tekrar düşünün.</strong> '+item.e}qScore.textContent='Doğru: '+score;qNext.textContent=qi===questions.length-1?'Sonucu göster':'Sonraki soru';qNext.hidden=false});
if(qNext)qNext.addEventListener('click',()=>{if(qi<questions.length-1){qi++;renderQuestion()}else{qText.textContent='Tamamlandı: '+score+' / '+questions.length;qOptions.innerHTML='';qFeedback.textContent=score===questions.length?'Tüm kararları doğru değerlendirdiniz.':'Yanlış cevapları gerekçeleriyle yeniden inceleyebilirsiniz.';qNext.textContent='Yeniden başla';qNext.onclick=()=>{qi=0;score=0;qNext.onclick=null;renderQuestion()}}});
renderQuestion();