const trNumber=(value,digits=1)=>Number(value).toLocaleString('tr-TR',{maximumFractionDigits:digits});
const celsius=fahrenheit=>(fahrenheit-32)*5/9;
const frostStages={
  budSwell:{name:'Tomurcuk şişmesi',ten:15,ninety:0},sideGreen:{name:'Yanlarda yeşil görünüm',ten:24,ninety:10},
  greenTip:{name:'Yeşil uç',ten:26,ninety:22},tightCluster:{name:'Sıkı küme',ten:26,ninety:24},
  openCluster:{name:'Açık küme',ten:28,ninety:24},firstWhite:{name:'İlk beyaz',ten:28,ninety:24},
  firstBloom:{name:'İlk çiçek',ten:28,ninety:24},fullBloom:{name:'Tam çiçek',ten:28,ninety:24}
};
const frostForm=document.querySelector('#frost-form');
if(frostForm)frostForm.addEventListener('submit',event=>{event.preventDefault();const stage=frostStages[document.querySelector('#frost-stage').value],temp=Number(document.querySelector('#frost-temp').value),ten=celsius(stage.ten),ninety=celsius(stage.ninety),result=document.querySelector('#frost-result');let level='low',title='Kritik eşiklerin üzerinde',detail='Tablodaki yaklaşık %10 hasar eşiğinin üzerinde; yine de bahçenin soğuk ceplerini izleyin.';if(temp<=ninety){level='high';title='Çok yüksek hasar riski';detail='Beklenen değer yaklaşık %90 hasar eşiğine eşit veya daha düşük.'}else if(temp<=ten){level='high';title='Hasar riski yüksek';detail='Beklenen değer yaklaşık %10 ile %90 hasar eşikleri arasında.'}else if(temp<=ten+1.5){level='watch';title='Eşiğe yakın: yakın izleme gerekir';detail='Tahmin küçük sapmalar gösterebilir; bahçe içi ölçüm ve koruma planı önemlidir.'}result.className=`smart-result risk-${level}`;result.innerHTML=`<strong>${title}</strong><p>${stage.name}: yaklaşık %10 hasar eşiği ${trNumber(ten)} °C, %90 hasar eşiği ${trNumber(ninety)} °C.</p><p>Girilen en düşük değer: <b>${trNumber(temp)} °C</b></p>`});

const sprayerForm=document.querySelector('#sprayer-form');
if(sprayerForm)sprayerForm.addEventListener('submit',event=>{event.preventDefault();const flow=Number(document.querySelector('#sprayer-flow').value),speed=Number(document.querySelector('#sprayer-speed').value),spacing=Number(document.querySelector('#row-spacing').value),tank=Number(document.querySelector('#sprayer-tank').value),litresHa=600*flow/(speed*spacing),litresDa=litresHa/10,coverage=tank/litresDa,result=document.querySelector('#sprayer-result');result.innerHTML=`<strong>Gerçek uygulama hacmi: ${trNumber(litresDa)} L/dekar</strong><div class="result-grid"><span><b>${trNumber(litresHa,0)} L/ha</b>hektara su</span><span><b>${trNumber(coverage,2)} dekar</b>bir depo ile alan</span><span><b>${trNumber(tank/flow)} dakika</b>depo boşalma süresi</span></div>`});

const phiDate=document.querySelector('#phi-date');if(phiDate)phiDate.value=new Date().toISOString().slice(0,10);
const phiForm=document.querySelector('#phi-form');if(phiForm)phiForm.addEventListener('submit',event=>{event.preventDefault();const raw=document.querySelector('#phi-date').value,days=Number(document.querySelector('#phi-days').value),date=new Date(`${raw}T12:00:00`),result=document.querySelector('#phi-result');date.setDate(date.getDate()+days);result.innerHTML=`<strong>En erken hasat: ${date.toLocaleDateString('tr-TR',{day:'numeric',month:'long',year:'numeric'})}</strong><p>${days} günlük etiket süresi, son uygulama tarihine eklenmiştir. Sonraki bir uygulama yapılırsa hesabı yeniden başlatın.</p>`});

const fertilizerForm=document.querySelector('#fertilizer-form');
if(fertilizerForm)fertilizerForm.addEventListener('submit',event=>{event.preventDefault();const bag=Number(document.querySelector('#fert-bag').value),count=Number(document.querySelector('#fert-count').value),price=Number(document.querySelector('#fert-price').value),area=Number(document.querySelector('#fert-area').value),trees=Number(document.querySelector('#fert-trees').value)||0,n=Number(document.querySelector('#fert-n').value),p=Number(document.querySelector('#fert-p').value),k=Number(document.querySelector('#fert-k').value),total=bag*count,cost=price*count,result=document.querySelector('#fertilizer-result');result.innerHTML=`<strong>${trNumber(total)} kg ürün · ${trNumber(cost/area,2)} ₺/dekar</strong><div class="result-grid"><span><b>${trNumber(total*n/100,2)} kg N</b>${trNumber(total*n/100/area,2)} kg/da</span><span><b>${trNumber(total*p/100,2)} kg P₂O₅</b>${trNumber(total*p/100/area,2)} kg/da</span><span><b>${trNumber(total*k/100,2)} kg K₂O</b>${trNumber(total*k/100/area,2)} kg/da</span></div><p>Toplam maliyet: <b>${trNumber(cost,2)} ₺</b>${trees?` · ağaç başına matematiksel maliyet: <b>${trNumber(cost/trees,2)} ₺</b>`:''}</p>`});

const routeForm=document.querySelector('#route-form');
if(routeForm)routeForm.addEventListener('submit',event=>{event.preventDefault();const rows=Number(document.querySelector('#route-rows').value),trees=Number(document.querySelector('#route-trees').value),requested=Number(document.querySelector('#route-samples').value),count=Math.min(requested,rows*trees),positions=[.18,.52,.82,.34,.68],points=[],seen=new Set();for(let i=0;i<count*5&&points.length<count;i++){const index=points.length,row=Math.max(1,Math.min(rows,Math.round((index+.5)*rows/count))),tree=Math.max(1,Math.min(trees,Math.round(positions[i%positions.length]*trees)));for(let offset=0;offset<trees;offset++){const candidate=((tree-1+offset)%trees)+1,key=`${row}-${candidate}`;if(!seen.has(key)){seen.add(key);points.push([row,candidate]);break}}}document.querySelector('#route-result').innerHTML=`<strong>${points.length} ağaçlık dengeli rota</strong><p>Sıraları aynı uçtan numaralandırın. Ağaç numarası, sıraya girdiğiniz taraftan sayılır.</p><ol>${points.map(([row,tree],index)=>`<li><b>${index+1}.</b> ${row}. sıra · ${tree}. ağaç</li>`).join('')}</ol>`});
